### ISSUE TITLE
[Request] Update images and resolve remaining to-do items in Fleet Server scaling docs

### ISSUE THREAD

**Issue by dedemorton** [elastic/ingest-docs#120]
## Description

We merged the Fleet Server scaling docs with some know issues: the images need more work, and there are some remaining TODO items flagged as comments in the source files.

We need to update the images and resolve the remaining TODO items.

## Collaboration

* [ ] The docs team will lead producing the content
* [x] The product team will provide the initial content and the docs team will edit / review
* [ ] The docs team will define with product team the structure and location, and the product team will provide the initial content
* [ ] Other (please describe)

**Contact Person:**

@nimarezainia 

## Suggested Target Release

7.16

**Comment by nimarezainia** [comment]
I think we are done with these for now. 'm sure there'll be more at some point :-)
