### ISSUE TITLE
META: Fix outdated screenshots and steps in Fleet & Agent docs (reported by QA)

### ISSUE THREAD

**Issue by kilfoyle** [elastic/ingest-docs#1242]
Here's the list of issues:

 - [x] https://github.com/elastic/ingest-docs/issues/1231 -> https://github.com/elastic/ingest-docs/pull/1581
 - [x] https://github.com/elastic/ingest-docs/issues/1232 -> https://github.com/elastic/ingest-docs/pull/1582
 - [x] https://github.com/elastic/ingest-docs/issues/1233 -> https://github.com/elastic/ingest-docs/pull/1583
 - [x] https://github.com/elastic/ingest-docs/issues/1234 -> https://github.com/elastic/ingest-docs/pull/1585
 - [x] https://github.com/elastic/ingest-docs/issues/1235 -> Already fixed by https://github.com/elastic/ingest-docs/pull/1264
 - [x] https://github.com/elastic/ingest-docs/issues/1236 -> Already fixed.
 - [x] https://github.com/elastic/ingest-docs/issues/1237 -> https://github.com/elastic/ingest-docs/pull/1586
 - [x] https://github.com/elastic/ingest-docs/issues/1238 -> https://github.com/elastic/ingest-docs/pull/1587
 - [x] https://github.com/elastic/ingest-docs/issues/1239 -> https://github.com/elastic/ingest-docs/pull/1588
 - [x] https://github.com/elastic/ingest-docs/issues/1240 -> https://github.com/elastic/ingest-docs/pull/1589

**Comment by kilfoyle** [comment]
All updated caps and steps have been merged and backported. Closing...

**Comment by amolnater-qasource** [comment]
Thank you @kilfoyle

**Comment by kilfoyle** [comment]
My pleasure @amolnater-qasource!

By the way, I really, really appreciate that you put the "expected" screenshots into the issues. That makes it easy for me since I don't have to recreate the environment. So in future I'll try to fix these sooner. :-). Thanks a lot for finding and reporting these problems!!!
