### ISSUE TITLE
[meta] Provide better Data Ingestion overview

### ISSUE THREAD

**Issue by ollyhowell** [elastic/ingest-docs#142]
### Motivation:
- Users find it difficult to understand and select the right data ingestion architectures for their use case
- Our existing Add date to Observability topic is incomplete and insufficient, especially in terms of Enterprise readiness
- We have a proliferation of data ingestion topics spread across different /guide books, with different content and heavy overlap, which adds pain for users and dilutes SEO juice e.g.
  - https://www.elastic.co/guide/en/observability/current/add-observability-data.html
  - https://www.elastic.co/guide/en/cloud/current/ec-cloud-ingest-data.html
  - https://www.elastic.co/guide/en/cloud-enterprise/current/ece-cloud-ingest-data.html
  - https://www.elastic.co/guide/en/kibana/8.1/connect-to-elasticsearch.html
- Internally, ingestion / architecture documentation is also incomplete, fragmented and hard to find / align against
- Onboarding 2.0 content in flight will add to the mix - more focus on 'getting data in' for simplest use cases but overlap and linking has to be well managed

### Outcomes
- Clear user-facing documentation on recommended ingest architectures
- Working concept for how to deal with the general case vs. specific solutions (e.g. Observability), and how to dovetail with Onboarding content (simple cloud-first GS vs everything else)
- Recommendations for reviewing/removing/updating existing related content

### Links

- https://docs.google.com/document/d/1m3oBUPRj-qBnj74Tf0rpxEATMMXPNaPhjm-qrHU-0Lo/edit
- https://docs.google.com/spreadsheets/d/1LDiiE83dxhsTYaH8krL0RdohJtcI-MTadI3K_XIGe5A/edit#gid=468513803
- https://docs.google.com/document/d/1XpNXErXdxqFErBgKo2KlEKz656PHEnJiXpdGdxpb7o0/edit#heading=h.eczetfui02wy
- https://docs.google.com/presentation/d/1a1kd59RQk27SirAm7sb0lKxq81i18zGKBOneX3BZjas/edit#slide=id.p1
- Reference Architecture Library https://docs.google.com/document/d/1jpPy3TPSPAUSgPTLEG-W0523e10bAYqGAFFuBWPkx00/edit#
- https://docs.google.com/document/d/1dnyvsqvxalXGHNX1Ng0vTskRVs6rEUan1rQrRVe5xi0/edit
- https://docs.google.com/document/d/130FS0k3Jn66COpM7vzBhONM-_zLs278p5IWvK9GoLMk/edit

### Tasks

- [ ] https://github.com/elastic/ingest-docs/issues/6
- [ ] https://github.com/elastic/ingest-docs/issues/7
- [ ] https://github.com/elastic/ingest-docs/issues/5
- [ ] @mukeshelastic to provide reference architecture [content](https://github.com/elastic/ingest-dev/issues/1177) 
- ...

### Related Issues
Add any issues/PRs that directly address this topic or contribute to the overall goal.
- [x] https://github.com/elastic/docs/pull/2461
- [x] https://github.com/elastic/tech-content/issues/229

**Comment by bmorelli25** [comment]
Removing from Obs-docs board but leaving open as there's likely still improvement that can be made here.
