### ISSUE TITLE
[META] Fix outdated screenshots in Fleet & Agent docs

### ISSUE THREAD

**Issue by kilfoyle** [elastic/ingest-docs#1546]
From QA:
 - [ ] https://github.com/elastic/ingest-docs/issues/1539
 - [ ] https://github.com/elastic/ingest-docs/issues/1540
 - [ ] https://github.com/elastic/ingest-docs/issues/1541
 - [ ] https://github.com/elastic/ingest-docs/issues/1542
 - [ ] https://github.com/elastic/ingest-docs/issues/1543

**Comment by omachala** [comment]
Hi! I can help with this screenshot audit.

I built [heroshot](https://heroshot.sh) for automating documentation screenshots - it captures them via Playwright so they can be regenerated when Fleet's UI changes.

Could tackle these systematically and include heroshot configs for future automation. Happy to help!
