### ISSUE TITLE
[Meta] Ingest architecture documentation for users

### ISSUE THREAD

**Issue by karenzone** [elastic/ingest-docs#2]
### Approach
This effort is broken into phases, but the work is NOT linear in nature. Some pieces will happen in parallel.

### Phase 1: Foundational/Discovery
* [x] Internal ingest architecture planning and documentation (@mukeshelastic, @jsvd)
   * [x] https://github.com/elastic/ingest-dev/issues/1177
* [x] New `ingest-docs` repo to handle cross-product content and issues(@karenzone)
* [x] Initial source file structure for user-facing ingest architecture guide (@karenzone) 
   * [x] #1 

### Phase 2: Release Strategy/Initial diagrams
* [x] #9 (@mukeshelastic, @karenzone)
* [x] #11 (@mukeshelastic/@karenzone/others?) 
   * [x] ToDo: Find out if at least some of these graphics exist already and can be repurposed 

### Phase 3: Add structure and start creating content (discovery continues)
* [x] #20 
* [x] #22
* [x] #25 
* [x] #3 (@karenzone)
  * [x] #10 
* [x] #4 (@karenzone)
* [x] #12  (@karenzone)
* [x] #13
* [x] #42

### Phase 4: Refine and improve content and graphics
* [x] #36
* [x] #43 
* [x] #47 (WIP)

### Next steps
* [x] #50
* [ ] Review cycles
   * [ ] SMEs (in progress)
   * [ ] Field
   * [ ] Users
* [ ] Make Phase 1 architectures available
* [ ] Open new meta issue for Phase 2

### Risks
Competing for resources. Many stakeholders with divided time/focus.
