### ISSUE TITLE
IngestArch: Create and add architecture graphics for Phase 1 architectures

### ISSUE THREAD

**Issue by karenzone** [elastic/ingest-docs#42]
Add high-level graphics for each architecture/use case

- [ ] 1 - EA to ES
   - [ ] 1a - EA installed
   - [ ] 1b APIs for collection
- [ ]  15 - EA to proxy to ES
- [ ]  EA to Logstash to ES
   - [ ] 10/11 - EA to Logstash (for enrichment) to ES
   - [ ] 12 - EA to Logstash (PQ for buffering) to ES
   - [ ] 14 - EA to Logstash (to bridge networks) to ES
   - [ ] 13 - EA to Logstash to multiple destinations
- [ ] 16 - EA to ES with Kafka as middleware message queue
   - [ ] 16a - Kafka to ES Sink
   - [ ] 16b - Kafka to Logstash
- [ ] Logstash to ES

**Comment by amitkanfer** [comment]
@karenzone I'm moving this to sprint 8 (7 is over)

**Comment by karenzone** [comment]
Completed in Sprint 7
