### ISSUE TITLE
Create outline for new Data Ingestion guide

### ISSUE THREAD

**Issue by ollyhowell** [elastic/ingest-docs#5]
Based on https://github.com/elastic/ingest-docs/issues/142, making separate issue for the outline / structure of proposed Data Ingestion guide.

### Links
Working draft (with multiple tabs/variants):  https://docs.google.com/document/d/1eqvXQfjIqksTCImO3yCnMDTOt6EM-lWkcACRLgSANds/edit#
Additional feedback/brainstorming doc: https://docs.google.com/document/d/1ggJICwcECedA3zXNOrodal8YVTXlDk9ZQuadpvX4sUg/edit

### Tasks
- [ ] Review and consolidate into one proposed version
- [ ] Identify content priorities and potential phased approach to publication
- [ ] Create new book in AsciiDoctor
