### ISSUE TITLE
[META] QA-reported issues with ingest docs

### ISSUE THREAD

**Issue by kilfoyle** [elastic/ingest-docs#671]
Creating a meta just to keep track of the current set of QA-reported docs issues in one place.

**New (2023-11-08):**
 - [x] [Fleet]: Edit Output Flyout screenshot not having yellow caution label. [#665](https://github.com/elastic/ingest-docs/issues/665) https://github.com/elastic/ingest-docs/pull/1008
 - [x] [Fleet]: Message under Diagnostics tab is not updated as per 8.11 [#670](https://github.com/elastic/ingest-docs/issues/670) https://github.com/elastic/ingest-docs/pull/1007
 - [x] [Fleet]: Diagnostics tab not available under Agent logs tab screenshot. [#669](https://github.com/elastic/ingest-docs/issues/669) https://github.com/elastic/ingest-docs/pull/1009
 - [x] [Fleet]: Add agent flyout screenshot is outdated under docs. [#668](https://github.com/elastic/observability-docs/issues/3739) - Transferred to observability-docs repo. https://github.com/elastic/observability-docs/pull/3740
 - [x] [Fleet]: Setup guide button is missing under Home page screenshot. [#667](https://github.com/elastic/observability-docs/issues/3743) https://github.com/elastic/observability-docs/pull/3744
 - [x] [Fleet]: Experimental badge is available and API reference tab is missing under Integrations screenshot.[ elastic/ingest-docs#663](https://github.com/elastic/ingest-docs/issues/663) https://github.com/elastic/ingest-docs/pull/1010
 - [x] [Fleet]: Edit Agent policy tab screenshot is outdated. [#661](https://github.com/elastic/ingest-docs/issues/661) https://github.com/elastic/ingest-docs/pull/1010
 - [x] [Fleet]: Screenshot not updated for Integrations tab as View deployment details updated to Endpoints. [#660](https://github.com/elastic/ingest-docs/issues/660) https://github.com/elastic/ingest-docs/pull/1011
 - [x] [Fleet]: The aforementioned screenshot for Cloud ID displays browser bookmarks. [#666](https://github.com/elastic/ingest-docs/issues/666) https://github.com/elastic/ingest-docs/pull/1012
 - [x] [Fleet]: Uninstall agent in action menu is missing under agents tab screenshot. [#664](https://github.com/elastic/ingest-docs/issues/664) https://github.com/elastic/ingest-docs/pull/1019
 - [x] [Fleet]: Uninstalled token tab is missing under agents tab in screenshots. [#662](https://github.com/elastic/ingest-docs/issues/662) https://github.com/elastic/ingest-docs/pull/1021
 - [x] Agent tamper protection feature docs are not available. [#676](https://github.com/elastic/ingest-docs/issues/676)

**Reopened (2023-11-08):**
 - [x] [Fleet]: Link icon is misaligned for elasticsearch and logstash output. [#230](https://github.com/elastic/ingest-docs/issues/230) - **Closed. This issue affects all docs and not just the Fleet & Agent Guide so, unfortunately, it's not something I can fix. :-(**

**Comment by kpollich** [comment]
@kilfoyle - Have we prioritized any of these issues here or completed any since this was filed? Wanted to bump this as the screenshots especially have been outdated for a bit now.

**Comment by kilfoyle** [comment]
Thanks for the bump @kpollich! I'd lost track of it so I'll make this one a priority.

**Comment by kilfoyle** [comment]
All of the screencaptures are fixed now. Thanks a lot for reporting all of these @amolnater-qasource! Sorry it took me a while to get to. :-)

**Comment by amolnater-qasource** [comment]
Thank you @kilfoyle for the fixes.
We will retest these issues once the fixes are available.

Thanks!
