### ISSUE TITLE
Complete competitive analysis of other data ingestion documentation

### ISSUE THREAD

**Issue by ollyhowell** [elastic/ingest-docs#7]
Based on https://github.com/elastic/ingest-docs/issues/142, making separate issue for completing the competitive analysis of how ingest content is structured across industry.

### Links
https://docs.google.com/presentation/d/1b83W-Uv_f_ATWXdJnP5vWf4PwsJjasxmshdQq6mDP_M/edit#slide=id.g1226724c94f_0_11

### Tasks
- [ ] Complete analysis and add remaining examples to deck
- [ ] Discuss different approaches and pros/cons
- [ ] Provide recommendations for general strategy and outline

### Questions
- [ ] Is this task still useful (and who should do it)?
